[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--legacy-peer-deps --no-audit"

[[plugins]]
  package = "@netlify/plugin-nextjs"
